### ISSUE TITLE
Try to deploy subgraphs to the The Graph hosted solution

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/subgraph#38]

**Comment by r-marques** [comment]
The subgraph name needs to be unique meaning that we cannot use the same name when deploying to multiple networks.

I think it would be best to use the same naming convention that is being use in the artifacts repo so for example:
- DIDRegistry on mumbai the subgraph name would be
```
nevermined-io/80001/common/v2.0.0/didregistry
```

**Comment by r-marques** [comment]
Turns out the hosted service does not accept special characters in the name and has a limit of 35 characters. Maybe we can do something like:
```
nevermined-io/mumbaiv200DIDRegistry
```
